SELECT	
	col.COLUMN_NAME
FROM	INFORMATION_SCHEMA.TABLE_CONSTRAINTS tab, INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE col
WHERE	col.CONSTRAINT_NAME	= tab.CONSTRAINT_NAME
AND		col.TABLE_NAME		= tab.TABLE_NAME
AND		tab.CONSTRAINT_TYPE	= 'PRIMARY KEY'
AND		col.TABLE_NAME		= ''